/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        appBg: "#f7f6f3",
        appElevated: "#ffffff",
        appMuted: "#efeee9",
        appText: "#37352f",
        appTextSecondary: "#6b6b66",
        appTextMuted: "#9b9a97",
        appBorder: "rgba(55, 53, 47, 0.09)",
        appBorderStrong: "rgba(55, 53, 47, 0.16)",
        accent: "#2383e2",
        accentHover: "#1a6fc9",
        accentMuted: "rgba(35, 131, 226, 0.12)",
        danger: "#e03e3e",
        dangerMuted: "rgba(224, 62, 62, 0.1)",
        success: "#0f7b6c",
        warning: "#cb912f",
        overlay: "rgba(55, 53, 47, 0.5)",
        practiceHeader: "#1a5f91",
        calloutBlue: "rgba(35, 131, 226, 0.10)",
        calloutYellow: "rgba(233, 168, 0, 0.12)",
        calloutPink: "rgba(226, 85, 161, 0.10)",
        calloutGreen: "rgba(15, 123, 108, 0.10)",
        calloutOrange: "rgba(217, 115, 13, 0.10)",
      },
      fontSize: {
        // Mobile Typography Scale (Chuẩn tỉ lệ hiển thị trên di động)
        "2xs": ["10px", { lineHeight: "14px" }],
        "badge": ["11px", { lineHeight: "15px" }],
        "caption": ["13px", { lineHeight: "18px" }],
        "body-sm": ["14px", { lineHeight: "20px" }],
        "body": ["15px", { lineHeight: "22px" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
        "title-sm": ["17px", { lineHeight: "24px" }],
        "title": ["19px", { lineHeight: "26px" }],
        "heading-sm": ["22px", { lineHeight: "28px" }],
        "heading": ["26px", { lineHeight: "32px" }],
        "display": ["32px", { lineHeight: "38px" }],
      },
      fontFamily: {
        sans: ["Inter_400Regular"],
        inter: ["Inter_400Regular"],
        "inter-medium": ["Inter_500Medium"],
        "inter-semibold": ["Inter_600SemiBold"],
        "inter-bold": ["Inter_700Bold"],
        "inter-extrabold": ["Inter_800ExtraBold"],
        "inter-black": ["Inter_900Black"],
      },
    },
  },
  plugins: [],
};
